# Generated by Django 2.0.7 on 2018-07-24 15:29

import bookshop.globals
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('address', models.CharField(max_length=100, verbose_name='Contact Address')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ('name',),
            },
            bases=(bookshop.globals.ModelGetFieldsMixin, models.Model),
        ),
    ]
