# Generated by Django 2.0.7 on 2018-07-24 15:29

import bookshop.globals
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
        ('wholesaler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Purchase Quantity')),
                ('datetime_purchase', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of Purchase')),
                ('remarks', models.TextField(verbose_name='Remarks')),
                ('authorised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Book')),
                ('whole_seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wholesaler.WholeSeller')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ('datetime_purchase', 'book'),
            },
            bases=(bookshop.globals.ModelGetFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_return', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Purchase')),
            ],
            bases=(bookshop.globals.ModelGetFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Sale Quantity')),
                ('datetime_sale', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of Sale')),
                ('remarks', models.TextField(verbose_name='Remarks')),
                ('authorised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='Book')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ('datetime_sale', 'book'),
            },
            bases=(bookshop.globals.ModelGetFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_return', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Sale', verbose_name='Sale Details')),
            ],
            bases=(bookshop.globals.ModelGetFieldsMixin, models.Model),
        ),
    ]
